<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.proj"/>

  <PropertyGroup>
    <AssemblyName>BeatyBit.Armature.Core</AssemblyName>
    <RootNamespace>BeatyBit.Armature.Core</RootNamespace>
    <DocumentationFile>$(SolutionDir)\.out\BeatyBit.Armature.Core.xml</DocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="nuspec">
    <description>The core part of the Armature framework, can be used to build your own framework with syntax and features of your choice</description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include=".build\Annotations.cs" />
    <Compile Include=".build\JetBrains.Annotations.cs" />
    <Compile Include=".build\Roslyn.CodeAnalysis.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BeatyBit.Bits" Version="0.0.20" />
  </ItemGroup>

</Project>
