<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.proj"/>

  <PropertyGroup>
    <RootNamespace>Armature.Test</RootNamespace>
    <AssemblyName>Armature.Test</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.3"/>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FakeItEasy" Version="8.3.0"/>
    <PackageReference Include="FluentAssertions" Version="7.2.0"/>
    <PackageReference Include="JetBrains.dotMemoryUnit" Version="3.1.20200127.214830"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0"/>
    <PackageReference Include="NUnit" Version="4.3.2"/>
    <PackageReference Include="NUnit.Console" Version="3.19.2"/>
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Armature.Core\Armature.Core.csproj"/>
    <ProjectReference Include="..\..\src\Armature\Armature.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include=".build\AssemblyInfo.cs"/>
  </ItemGroup>
</Project>