<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(SolutionDir)\.build\beatybit.public.snk</AssemblyOriginatorKeyFile>
    <PublicSign>true</PublicSign>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFrameworks>net472;net9.0</TargetFrameworks>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.3"/>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FakeItEasy" Version="8.3.0" />
    <PackageReference Include="FluentAssertions" Version="7.2.0" />
    <PackageReference Include="JetBrains.dotMemoryUnit" Version="3.1.20200127.214830"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Console" Version="3.19.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Armature.Core\Armature.Core.csproj"/>
    <ProjectReference Include="..\..\src\Armature\Armature.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include=".build\AssemblyInfo.cs"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(SolutionDir)\.build\beatybit.public.snk">
      <Link>.build\armature.public.snk</Link>
    </None>
  </ItemGroup>
</Project>
