name: Build & Test

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - 'feature/**'
    - 'release/**'
#  pull_request:
#    branches: [ master ]

env:
  configuration: Release
  artifacts-dir: artifacts
  nugets-dir:    artifacts/nupkgs
  pdb-dir:       artifacts/pdb

jobs:
  build:
    runs-on: windows-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    -
      name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'

    -
      name: Use GitVersion
      id:   gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.11

    -
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:     6.0.x
        include-prerelease: true

    # Build
    -
      name: Build
      run:  >
            dotnet build
            -c ${{env.configuration}}
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }}
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}

    # Run tests
    -
      name: Test
      run: dotnet test --no-build

    # Create and place nuget packages into env.nugets-dir directory
    -
      name: Pack
      run: dotnet pack --no-build -o:${{ env.nugets-dir }} -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

    -
      name: Store Version
      uses: jsdaniell/create-json@1.1.2
      with:
        name: version.json
        json: |
              {
              "assembly-version": "${{ steps.gitversion.outputs.assemblySemVer }}",
              "assembly-file-version": "${{ steps.gitversion.outputs.assemblySemFileVer }}",
              "nuget-version": "${{ steps.gitversion.outputs.nuGetVersionV2 }}"
              }
        dir:  ${{ env.artifacts-dir }}

    -
      name: Store PDB
      run: |
            robocopy src\Armature\bin\Release\netstandard2.0\ ${{ env.pdb-dir }} *.pdb
            if ($lastexitcode -lt 8) { $global:lastexitcode = 0 }

    -
      name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name:           Artifacts
        path:           ${{ env.artifacts-dir }}/
        retention-days: 3